"""Zero migration

Revision ID: 55786619813e
Revises:
Create Date: 2025-03-09 23:09:23.812419

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "55786619813e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "passwords",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("hash", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hash"),
    )
    op.create_index(
        "password_hash_idx", "passwords", ["hash"], unique=False, postgresql_using="hash"
    )
    op.create_index("password_id_idx", "passwords", ["id"], unique=False, postgresql_using="hash")
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("is_disabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("name"),
        sa.CheckConstraint(
            "email ~ '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'", name="check_email_format"
        ),
    )
    op.create_index("user_email_idx", "users", ["name"], unique=False, postgresql_using="hash")
    op.create_index("user_id_idx", "users", ["id"], unique=False, postgresql_using="hash")
    op.create_index("user_name_idx", "users", ["name"], unique=False, postgresql_using="hash")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("user_name_idx", table_name="users", postgresql_using="hash")
    op.drop_index("user_id_idx", table_name="users", postgresql_using="hash")
    op.drop_index("user_email_idx", table_name="users", postgresql_using="hash")
    op.drop_table("users")
    op.drop_index("password_id_idx", table_name="passwords", postgresql_using="hash")
    op.drop_index("password_hash_idx", table_name="passwords", postgresql_using="hash")
    op.drop_table("passwords")
    # ### end Alembic commands ###
