"""model fixes

Revision ID: fe3e1a1bdcea
Revises: 55786619813e
Create Date: 2025-03-09 23:15:47.701168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe3e1a1bdcea'
down_revision: Union[str, None] = '55786619813e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passwords', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'passwords', ['user_id'])
    op.create_foreign_key(None, 'passwords', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index('user_email_idx', table_name='users', postgresql_using='hash')
    op.create_index('user_email_idx', 'users', ['email'], unique=False, postgresql_using='hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_email_idx', table_name='users', postgresql_using='hash')
    op.create_index('user_email_idx', 'users', ['name'], unique=False, postgresql_using='hash')
    op.drop_constraint(None, 'passwords', type_='foreignkey')
    op.drop_constraint(None, 'passwords', type_='unique')
    op.drop_column('passwords', 'user_id')
    # ### end Alembic commands ###
